import ConvexClientProvider from "@/components/shared/ConvexClientProvider";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import Header from "@/components/shared/Header";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Confetti } from "@/components/shared/Confetti";
import { inter, bruno_ace_sc } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen flex flex-col bg-background",
          inter.className,
          bruno_ace_sc.className,
        )}
      >
        <NextTopLoader showSpinner={false} color="#E7B008" />
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="container py-2 h-fit md:py-18 grow">{children}</div>
            <Toaster />
            <Confetti />
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
